### ISSUE TITLE
Error: Call: more than 50 freq

### ISSUE THREAD

**Issue by UnderwaterHockey** [robotastic/trunk-recorder#104]
I just updated, and I'm still getting a lot of these errors.  
![screenshot from 2017-03-11 15-24-19](https://cloud.githubusercontent.com/assets/25648498/23827042/b1a01616-066f-11e7-815a-de5c8486fb63.png)

**Comment by UnderwaterHockey** [comment]
new screenshot
![screenshot from 2017-03-11 20-58-13](https://cloud.githubusercontent.com/assets/25648498/23828630/d72e4dde-069d-11e7-9e5f-5b6d8be62c45.png)

**Comment by UnderwaterHockey** [comment]
New error
![screenshot from 2017-03-11 23-34-02](https://cloud.githubusercontent.com/assets/25648498/23829262/556c592e-06b3-11e7-8b18-a653d2bd7a2c.png)

**Comment by UnderwaterHockey** [comment]
Config

**Comment by geeojr** [comment]
I have this same issue and a potential cause.

In my case it appears to be caused when I'm monitoring multiple linked trunked systems that are carrying traffic for the same talkgroup at the same time. It seems to ping-pong between both towers/frequencies and leaves quite a bit of noise in the recording. If I remove one or more of the systems from the configuration file the issue goes away since it only sees one instance of the call. I'm happy that the system doesn't record the call twice; but it probably just needs to disregard the second duplicate transmission on the second system in this case. 

Let me know if you need more details or maybe a reference to the system on radioreference, etc.

**Comment by UnderwaterHockey** [comment]
Try the development branch.  He made a change there that distinguished the two systems, it seems to be working much better for me.

**Comment by robotastic** [comment]
I think this should be fixed. Closing, but re-open if it is still an issue.
