### ISSUE TITLE
"audioArchive": false - metadata files remain

### ISSUE THREAD

**Issue by blantonl** [robotastic/trunk-recorder#338]
With "audioArchive" set to false metadata files still remain when uploading calls to Broadcastify.  

This results in directories full of metadata json files.

**Comment by JustApu** [comment]
I noticed the same thing as I started uploading to Broadcastify. That said, I can see some value in having that data locally. I would suggest that "metadataArchive" be a separate option and not linked entirely to the "audioArchive" setting.

**Comment by robotastic** [comment]
I hadn't run into this before. The `callLog` feature lets you turn off json generation, but for Broadcastify you need the json file. `audioArchive` only refers to the audio files. Coming up with a `callLogArchive` seems like the best path. This would let you selectively delete the json. I could see instance where you want the audio and not the json too. I will see if I can make this addition.

**Comment by Ares4570** [comment]
After updating to the latest version that includes this, I'm now seeing an issue with duplicate call handling. BCFY generates an error (Broadcastify Metadata Upload Error: SKIPPED---ALREADY-RECEIVED-THIS-CALL) if a call has already been submitted, but this error seems to result in the call (both recording and JSON) being retained rather than deleted as they should be.
