### ISSUE TITLE
Failing to record trunked audio

### ISSUE THREAD

**Issue by KyleKotowick** [robotastic/trunk-recorder#508]
I recently upgraded from v3.0.1 to v3.3.7 and am experiencing an issue where the system can decode the control channel messages, but is not recording any audio from any conversations.

Here is an example of the output I'm getting:
```
[2021-09-03 14:14:38.701452] (info)   [Trunked] TG:       1227  Freq: 851.125000 MHz    Starting Recorder on Src: hackrf=7595cf
[2021-09-03 14:14:44.008714] (trace)   [Trunked]        TG:       1227  Freq: 851.125000 MHz    Ending Recorded Call - Last Update: 4s        Call Elapsed: 6
[2021-09-03 14:14:44.009158] (info)     - Stopping P25 Recorder Num [1] TG:       1227  Freq: 851.125000 MHz TDMA: false      Slot: 0
[2021-09-03 14:14:44.009302] (error)   wav error closing file
[2021-09-03 14:14:44.009362] (info)   [Trunked] Deleting this call as it has a duration less than minimum duration of 0       TG:       1227  Freq: 851.125000 MHz    Call Duration: 0s
[2021-09-03 14:14:44.009496] (error)   Could not delete file recordings/Trunked/2021/9/3/1227-1630692878_851125000.wav
```

As you can see, it's detecting the control channel message that a transmission has started and is tuning to the frequency for it, but is failing to actually record any audio. It then seems to fail to close the `wav` file, and then tries to delete that file and fails on that too.

I thought this might be a tuning/error/ppm issue so I've played with the PPM setting in both directions until it can't read the control channel anymore, but it has the same issue.

Occasionally, if I restart the software, it works normally and continues to work normally, but I'd say that 2/3 of the time it fails with these errors.

Any thoughts @robotastic?

**Comment by kd4e** [comment]
Any chance permissions changed for some reason?


The "... wav error closing file" and "Could not delete file ..." type 
errors have often proved
to be permissions related, for me.

Also, the "Deleting this call as it has a duration less than minimum 
duration of 0" seems a
bit funky - if it couldn't save to a .wav file due to a permissions 
error, that might trigger
the other error (length).


> On 9/3/21 2:19 PM, Kyle Kotowick wrote:  > > I recently upgraded from v3.0.1 to v3.3.7 and am experiencing an > 
issue where the system can decode the control channel messages, but > is 
not recording any audio from any conversations. > > Here is an example 
of the output I'm getting: > > |[2021-09-03 14:14:38.701452] (info) 
[Trunked] TG: 1227 > Freq: 851.125000 MHz Starting Recorder on Src: 
hackrf=7595cf > [2021-09-03 14:14:44.008714] (trace) [Trunked] TG: > 
1227 Freq: 851.125000 MHz Ending Recorded Call - Last Update: 4s > Call 
Elapsed: 6 [2021-09-03 14:14:44.009158] (info) - Stopping > P25 Recorder 
Num [1] TG: 1227 Freq: 851.125000 MHz TDMA: false > Slot: 0 [2021-09-03 
14:14:44.009302] (error) wav error closing > file [2021-09-03 
14:14:44.009362] (info) [Trunked] Deleting this > call as it has a 
duration less than minimum duration of 0 TG: > 1227 Freq: 851.125000 MHz 
Call Duration: 0s [2021-09-03 > 14:14:44.009496] (error) Could not 
delete file > recordings/Trunked/2021/9/3/1227-1630692878_851125000.wav 
| > > As you can see, it's detecting the control channel message that a 
 > transmission has started and is tuning to the frequency for it, but > 
is failing to actually record any audio. It then seems to fail to > 
close the |wav| file, and then tries to delete that file and fails on > 
that too. > > I thought this might be a tuning/error/ppm issue so I've 
played with > the PPM setting in both directions until it can't read the 
control > channel anymore, but it has the same issue. > > Occasionally, 
if I restart the software, it works normally and > continues to work 
normally, but I'd say that 2/3 of the time it fails > with these errors. 
 > > Any thoughts @robotastic <https://github.com/robotastic>? > > — You 
are receiving this because you are subscribed to this thread. > Reply to 
this email directly, view it on GitHub > 
<https://github.com/robotastic/trunk-recorder/issues/508>, or > 
unsubscribe >

**Comment by KyleKotowick** [comment]
@kd4e I've tried running the recorder as sudo/root and it has the same issue, so I can't see how it would be permissions related.

**Comment by KyleKotowick** [comment]
@robotastic It works occasionally, without changing the config file. Can't link it to anything specific.

**Comment by robotastic** [comment]
This sounds like it is a tuning issue then. Either the error or gain setting could be off. They sometimes can change over time. I recently had to update the error on an SDR because it stopped working. This was one of the nicer ones that is supposed to correct for error.

**Comment by KyleKotowick** [comment]
I suppose that must be it, since it's an intermittent issue that starts and stops on its own with no changes to the software, config, or OS. Odd that it is able to capture the control channel messages but not the audio messages on other trunk channels.

**Comment by aaknitt** [comment]
I'm seeing the same issue & symptoms on a new installation built from source on a Pi4 with an SDR with TCXO.  I haven't yet had it generate any WAV files at all, but seeing the same error messages as OP.  Control channel decoding is working.

**Comment by aaknitt** [comment]
> @aaknitt Generally this is a configuration issue. Try setting `controlWarnRate` to 0, in the top level of the config.json file. This will tell you how many control channel messages you are actually receiving. It should be around 30 or 40 per sec. It may also be worth checking to see if you have the modulation correct. Even with TCXO, sometimes there can be a little error and the voice channels can be more sensitive than the control channel. The other knob is the gain, make sure it is adjust correctly. Finally, unless you are recording Analog, remove any squelch settings.

@robotastic thanks that's helpful.  Looks like I'm getting decent numbers of control channel messages.  I also played with the ppm a bit and adjusting it much off of zero in either direction seems to make things worse, with PDU timeouts at -1ppm and +2ppm.  Otherwise settings are all copied from another (much older) instance of trunk-recorder I have running on an Ubuntu computer using the same type of dongles on the same system.  So the difference are 1) Pi 4 vs. Ubuntu desktop and 2) version of trunk-recorder.  I think I have another Pi with an older version of trunk-recorder installed on it around, maybe I'll try the same config.json and dongle on that one and see what happens.  
![image](https://user-images.githubusercontent.com/13441553/136388261-fabd6918-cbba-476b-90e8-21989c528219.png)

**Comment by aaknitt** [comment]
I just cloned and built the 4.0-beta branch and that's working correctly (creating audio files) on the same setup that was failing with v3.3.7

**Comment by aaknitt** [comment]
but 4.0-beta seems to have changed the unitScript functionality (changed to a plugin?) which is something I was planning on using...not sure how the plugin stuff works.

**Comment by KyleKotowick** [comment]
I haven't used the 4.0 beta yet, but I saw somewhere that it changes the recording format to be per-transmission recordings? I can't try that out now as that change would break all our existing infrastructure.

I'm not a great person to test this, because I can't reproduce the issue consistently. Seems to happen once a week or so.

**Comment by aaknitt** [comment]
@robotastic thanks, I see that you made some changes related to unitScript today.  I realize I'm hijacking this thread, but I grabbed the latest and built.  As best I can tell when trunk-recorder starts it seems to recognize that there's a unitScript associated with my system in the config.json file, but it doesn't ever seem to be executing.  
![image](https://user-images.githubusercontent.com/13441553/136463493-63f7c96b-678f-444e-a387-b0f59b2559d2.png)
Are there any changes in how I need to configure my script or the config.json file?  It looks something like this in config.json (yes I'm using the same script for unitScript and uploadScript, and it fires correctly when it should for uploadScript):

`    "systems": [{
        "control_channels": [853712500,853687500,853350000,853137500],
        "type": "p25",
		"modulation": "qpsk",
		"digitalLevels":8,
		"shortName": "oasiswauk",
		"talkgroupsFile": "OASISTG.csv",
		"uploadScript":"myscript.py",
		"unitScript":"myscript.py",
		"recordUnknown": false,
		"audioArchive": true,
		"talkgroupDisplayFormat": "id_tag"`

**Comment by aaknitt** [comment]
As a final follow up on this issue for those that may come across it:

Against advice, I had built trunk-recorder 3.3.7 in the cloned directory rather than creating a separate build directory.  I removed it completely and rebuilt per the recommended method and it's now working without the WAV error.
