### ISSUE TITLE
Readme mentions google groups, is that still a thing ?

### ISSUE THREAD

**Issue by hayden-t** [robotastic/trunk-recorder#519]
As it doesnt load for me , I thought GG was dead ?

**Comment by hayden-t** [comment]
Yeah I knew that, I was more suggesting that It should be removed from the readme if not still active.

**Comment by robotastic** [comment]
Yep! I am actually working on that right now. The docs are being reviewed and updated for the v4.0 branch. I am going to include basic instructions for installation in the repo itself and then point to the Wiki for more indepth articles.

This will be fixed in v4.0 - and I think I may have remove the Google Groups in the last push.
