### ISSUE TITLE
The rdio-scanner plugin does not send the freq_list with spike_count and error_count

### ISSUE THREAD

**Issue by chuot** [robotastic/trunk-recorder#602]
I just realized that the rdioscanner-plugin does not send the freq_list with the number of spikes and errors in the frequency field, so Rdio Scanner always shows "E: 0 S: 0" instead of the proper data.

I am however a little confused on how to bring this data to the uploader. What would be the right way to do this, add the information in `Call_Data_t`?

**Comment by aaknitt** [comment]
Looks like when the plugin system was put in place that info didn't make it into the JSON in the same way that it used to be either:
https://github.com/robotastic/trunk-recorder/commit/4daac16a0cfea8bd34ad4d64db75abb12086e19f#diff-27578a9e34f9eb8cfcc62585171ceb71273ff44aa16f05c5f51e40322e58f2f3

So there is a freqList object available in the JSON file but it's not actually getting populated with all of the data from the freq_list.  Error Count and Spike Count look like they're hard-coded to zero and only one frequency is making it in there, the list isn't being accessed and looped through to populate the JSON data.  

I think you're correct that the freq_list information needs to get added to the Call_Data_t structure and then populated in call_concluder.cc.  The JSON generation should also loop through that same info to pull out everything from the list so that it's available there in addition to via the plugin system.
