### ISSUE TITLE
Explain how to find center frequency

### ISSUE THREAD

**Issue by timothyclemansinsea** [robotastic/trunk-recorder#82]

**Comment by rosecitytransit** [comment]
Figure out the range of spectrum that you want to be able to record from (by finding the lowest and highest voice frequencies that are in use and expanding a little bit on either side), subtract the two and then divide by two.

The center frequency is what the radio gets tuned to, and the program will be able to record from frequencies that are within less than half of the sample rate on either side of it.  Note that I think it might be good to not have the center frequency be on an actual voice or control channel due to interference.
